language: generic
if: "(type = push AND branch IN (master, develop)) OR type IN (pull_request, api, cron)"
jdk:
- openjdk8
services:
- docker
before_install:
- curl -L http://dl.bintray.com/snowplow/snowplow-generic/schema_ci_0.2.0.zip | jar xv && chmod +x ./schema-ci

jobs:
  include:
  - stage: Test
    name: Unit Tests
    script: echo "Pretending to run unit tests..."
  - name: Integration Tests
    script: echo "Pretending to run integration tests..."
  - stage: Build
    name: Build
    script: echo "Pretending to build and push artifacts..."
  - stage: Deployment Requirements
    if: branch IN (master, develop)
    name: Check Deployment Requirements
    env:
    - ENV=$(if [ "$TRAVIS_BRANCH" = "master" ]; then echo "PROD"; else echo "DEV"; fi)
    script:
    - './schema-ci check --manifestPath $TRAVIS_BUILD_DIR/snowplow-schemas.json
      --username $USERNAME --password $PASSWORD --environment $ENV 2>/dev/null'
  - stage: Deploy
    if: type = push AND branch IN (master, develop)
    name: Deployment
    script: echo "Prepare deployment..."
    deploy:
      skip_cleanup: true
      provider: script
      script: echo "Pretending to deploy..."
      on:
        condition: type = push AND branch IN (master, develop)
env:
  global:
  - AUTH_SERVER_BASE_URL="https://snowplow-next.eu.auth0.com"
  - API_BASE_URL="https://next.console.snowplowanalytics.com"
  - secure: "hbm2TOKuhQ5AUUM+z3I1VAgviI6LhU56VvXDYMr2etGildS6Tj0J3sIJMeHcgNsXzY0YvJvTw20jVqR0Q4fk7bmnHh2ZGl6O9R44EZ10pQk0LbE8N2xob2X+fkNepI1m08cd3fGtso8POg19X08yRJZ6nIH04OjDwoZH8pmlhSL9tdFV5reneRjFsXk6VySgq4Qpp/tnIMt//OtdjWGSEMckuGzZyWwsXEN9dfB0RQ1ecR8jXGR8Npzg5nk0il9kq7Ip2gLYIJpLXeVIfEJ0byFvNDpAruLxwnR7AF1RhymUdroSIomG+/9iTD2kGri1mFqSjXwjDpDav2ggnVef+8zUhwBqrH5NzsZV1CLdwn7Ogxy6LBTn/QDy6s2OI295FrBFGHH7jub3nLk1AP3N7MhZKishOjz4rxtVsfAhfnN4ImbY9/YLHfhvFwryG6p9arrX4VYBhdfePvjpabb5JWH+5F/XNuTuXLWklBQ8rhQxYTQoH5sAzI/yqGgiaGPrXppeqKVY7pvTHWLHCmjmjdUNlAmwLRIDHRifwvFS7XJ7HajdI8DjF1GFIyTeR2tva4BNRVun4hXO5DFXPX71JRTuKorVpUVsok88zHXb3hfchwbGciChfeII/ubk1CiV/cp1bzKYGSuyrrmvWugmN990q1XQRq73YjvquI2o1gY="
  - secure: "Ltv3YhLBn2L2NzXTfQH1GMpko4DG03ngxJxJIS+e5+gNRDh7OCoR9xmGzDaMpBr2KwU4BweCdtX5aj8LtgfC6mShcVw1+71PgCgARLvGsZ4fX3MfPA6Pg30M7sITwZLDqtzSJQDQ/PQK9T7mDXMUy9Jbp/VmqVNWAHjjdYG8CdBVSUXzSEqRMOBVNdIm62fbyBLrSKBXAHxPLO6xOfDoajnpEdY+hJLYtxAsV1DesddXNB6gug5t5GfTgkXiSm9Ijsvz/GnVcQSSYKlkr/MYaZMP02u0C25LQ7Kh0GW5AHr9+p/vcRzC/fqNU/7XhOvQhgLmHWD87sL6qq6SQtU4M2B3siPIFQ7Qqbz51s/P6sc7i+dDIvCj6J6a8sd+/jwQEhT5ClXjcLrZwEpknJS+Ais97S273bpcrgKLQkCLlugo6mEUu5zXdNaJhkYirP00Tl4b4F2OhJwc7b2zPdH2rfDnPr3XfZRn6eAa8Oa+5AQEKfSIE7CPbWxYJwwcz6rXPEkyfyk3j2nX7xITPO+03DsFQDVdDr1doWqo5JswPClq2KaYnbI7cXI37AlrlylUQsk59qZO4RyhxLfs6SmH4dkAW8ro2W2qT/E7zObJSnkNgRnGgop5butblEo286df/sCIGQ1yKtQIX9jm+7S3D91IKou29gZz7YHGfjzseD0="
  - secure: "PeXr1ZxmTwHXwL2wwvKJZb90b504L5xPXKj2obel3zVFa3QFLo1hsyQZXH4rzyF3LLs3wNKi7vzpS3u2qlDFeVp8WywefRz3kP8afMmLaBzWIqAtX3fdAPx7DBfSU3BeAoRjpirTO0OkZNq3hzht0+9UDmDIXEN6tpJnv604yOuYcIRBDdOSoGOFkpBP/GualcP8MfzI3jnBHUs/YATwviLV9QWPfA9mGbprgzMqzejHPlBlG8hYBvuSaSxo4tyeCYmnmTyP60ilNHgY4piHdrqt77riN0Y6ZaAbiMiXisE1i4XJDJUBq2RSYji8suKGtOGslCyn9sedDWMenkW8bTqfNMm1qbZZeDqTSOYMPIqTluQF1M7q0c/NWfgm6P8e8+4FJl9ToUU9LqnfaNEKXcx861Z5qbREglK3jqM/ayLjaeI2ynGAvq3Yk1pEAIXfdhK4rvViY1SkmSvm/TidRIgsvQj6v1bTU3Uvxu8iowBXJoWcbJpNzP/shYsvzcXvts7dYQW2VumAVLym8dZPJUZVPnzlcMC+FoaNuN+QV/zryX+g9Ua86pZzkUSZ6caw6vDQ9GuukgrDAWxQGpod95v0n5EuhpKWwu5Xr/ffM0eDuktDDLtag6xkUAEMYrUwlC1vtNC5QqW/oSZEfEKowLpe0SFoheYrkweEUSQ13zQ="
  - secure: "gzHDwmsNcCbvy2rG08rM2Xhjwc9UFFbMzPbhW49DjwKfqmE1ILQJbeaHluWD0BOCl1rTV9ovDImZpT36EckoTn+GLQjakAzRyXk24one9vfmPIyfYUbCLKw6tkOGOKyURl+AFLRBTUWxkI/ormpS+AkB7cWOSBwjo3YcQTKjuLziEew89celUFg1TygurxOEXK4Cf+NkkQhTQfZtHoHl5cDtOt/8s3bwEbJ1etc1bDOdG+PHaLTZuEtIrWi4nrQITb5Cw83ddlKx2pQrbaBi+LBZIFNtjP8M1BPAZaA72cBtAwdWWqWkGwzivBD347/ejmN4oTrRDVLcPNpXCGByWAK7t30zSMDHj1hF99E3TEKf6BlhbMlS7Fc5EEBy5lT42V0IEUorhk2MBxewNvn1oBzC1mQYarEPy154z1qiSljlzsB6Fhie9/7LvgAhLYX34LXXarHLC8EHmJoiYKZP1dBXbqN+q0IoY/FSdVlW/nDlPg94T6K0dEPkZ4enGKXG/2C4O+MkINEgOKJfAKVxWJn8IaeB8leZZj6ZfY6V5SNpEEhV5uQ4QOKcTqqSg4Rsihd8pJWtURh2f5Ci4WZYTuq1XXz7DkWQkvjP/g1ZXCQoPibXBZmTTB1qRP6eOzAl5j/5KM5SaYLSiZQ03owlycfUtKZgIRmkssUzdLTkFOk="
  