name: ci

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    
    - name: Unit Tests
      run: echo "Pretending to run unit tests..."

    - name: Integration Tests
      run: echo "Pretending to run integration tests..."

    - name: Build
      run: echo "Pretending to build artifacts..."

    - name: Release
      run: echo "Pretending to push artifacts..."
  
  deploy-requirements:
    runs-on: ubuntu-latest
    name: Verify deployment requirements
    if: (github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'develop')) || (github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop'))

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch and environment
      run: |
          export BRANCH=$(if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then echo $GITHUB_BASE_REF; else echo $GITHUB_REF; fi)
          echo "Target branch is $BRANCH"
          echo "::set-env name=BRANCH::$BRANCH"
          export ENV=$(if [ "$BRANCH" = "master" ]; then echo "PROD"; else echo "DEV"; fi)
          echo "Target environment is $ENV"
          echo "::set-env name=ENV::$ENV"

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Run Snowplow's Schema CI
      uses: snowplow-product/msc-schema-ci-action/check@master
      with:
        manifest-path: snowplow-schemas.json
        organization-id: 75ea1aeb-4379-4958-8cbb-1a5cefbb4d29
        auth-client-id: YCE5aZubvHRZ7hqF0B1XxwRR3cAApu9G
        auth-client-secret: ${{ secrets.CLIENT_SECRET }}
        auth-audience: https://snowplowanalytics.com/api/
        auth-username: YCE5aZubvHRZ7hqF0B1XxwRR3cAApu9G@costas.gr
        auth-password: ${{ secrets.USER_PASSWORD }}
        environment: ${{ env.ENV }}
      env:
        AUTH_SERVER_BASE_URL: https://snowplow-next.eu.auth0.com
        API_BASE_URL: https://next.console.snowplowanalytics.com

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop')
    needs: [ build, deploy-requirements ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy
      run: echo "Pretending to deploy to $ENV..."