name: ci

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    
    - name: Unit Tests
      run: echo "Pretending to run unit tests..."

    - name: Integration Tests
      run: echo "Pretending to run integration tests..."

    - name: Build
      run: echo "Pretending to build artifacts..."

    - name: Release
      run: echo "Pretending to push artifacts..."
  
  deploy-requirements:
    runs-on: ubuntu-latest
    name: Verify deployment requirements
    if: (github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'develop')) || (github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop'))

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch and environment
      run: |
          export BRANCH=$(if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then echo $GITHUB_BASE_REF; else echo $GITHUB_REF; fi)
          echo "Target branch is $BRANCH"
          echo "::set-env name=BRANCH::$BRANCH"
          export ENV=$(if [ "$BRANCH" = "master" ]; then echo "PROD"; else echo "DEV"; fi)
          echo "Target environment is $ENV"
          echo "::set-env name=ENV::$ENV"

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Install dependencies
      run: |
        sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.0.4/2.13-2.0.4) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
    
    - name: Verify all used schemas are deployed
      env: 
        ORGANIZATION_ID: 75ea1aeb-4379-4958-8cbb-1a5cefbb4d29
        CLIENT_ID: YCE5aZubvHRZ7hqF0B1XxwRR3cAApu9G
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        AUDIENCE: https://snowplowanalytics.com/api/
        USERNAME: YCE5aZubvHRZ7hqF0B1XxwRR3cAApu9G@costas.gr
        PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        amm scripts/verify-schema-deployment.sc \
        --manifestPath $GITHUB_WORKSPACE/snowplow-schemas.json \
        --organizationId $ORGANIZATION_ID \
        --clientId $CLIENT_ID \
        --clientSecret $CLIENT_SECRET \
        --audience $AUDIENCE \
        --username $USERNAME \
        --password $PASSWORD \
        --environment $ENV

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop')
    needs: [ build, deploy-requirements ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy
      run: echo "Pretending to deploy to $ENV..."